using System.Text.Json.Serialization;
using Authagonal.Core.Models;
using Authagonal.Server.Endpoints;
using Authagonal.Server.Endpoints.Scim;
using Authagonal.Server.Middleware;
using Authagonal.Server.Services;
using Authagonal.Server.Services.Cluster;

namespace Authagonal.Server;

[JsonSerializable(typeof(DeviceCodeData))]
[JsonSerializable(typeof(AuthorizeEndpoint.ConsentData))]
[JsonSerializable(typeof(WebAuthnCredentialData))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(VaultResponse<SignResponse>))]
[JsonSerializable(typeof(VaultResponse<VerifyResponse>))]
[JsonSerializable(typeof(VaultResponse<TransitKeyInfo>))]
[JsonSerializable(typeof(VaultResponse<EncryptResponse>))]
[JsonSerializable(typeof(VaultResponse<DecryptResponse>))]
[JsonSerializable(typeof(VaultResponse<HmacResponse>))]
[JsonSerializable(typeof(VaultResponse<HmacBatchResponse>))]
[JsonSerializable(typeof(VaultResponse<EncryptBatchResponse>))]
[JsonSerializable(typeof(VaultResponse<DecryptBatchResponse>))]
[JsonSerializable(typeof(VaultSignRequest))]
[JsonSerializable(typeof(VaultVerifyRequest))]
[JsonSerializable(typeof(VaultEncryptRequest))]
[JsonSerializable(typeof(VaultDecryptRequest))]
[JsonSerializable(typeof(VaultHmacRequest))]
[JsonSerializable(typeof(VaultHmacBatchRequest))]
[JsonSerializable(typeof(VaultEncryptBatchRequest))]
[JsonSerializable(typeof(VaultDecryptBatchRequest))]
[JsonSerializable(typeof(VaultCreateKeyRequest))]
[JsonSerializable(typeof(VaultKeyConfigRequest))]
[JsonSerializable(typeof(ErrorResponse))]
// Common response DTOs
[JsonSerializable(typeof(ApiError))]
[JsonSerializable(typeof(ApiErrorDetail))]
[JsonSerializable(typeof(SsoRedirectError))]
[JsonSerializable(typeof(LockedOutError))]
[JsonSerializable(typeof(RegistrationSuccess))]
[JsonSerializable(typeof(ScimError))]
// Endpoint response DTOs (trim-safe replacements for anonymous types)
[JsonSerializable(typeof(SuccessResponse))]
[JsonSerializable(typeof(LogoutResponse))]
[JsonSerializable(typeof(SuccessMessageResponse))]
[JsonSerializable(typeof(MessageResponse))]
[JsonSerializable(typeof(RedirectResponse))]
[JsonSerializable(typeof(ErrorInfoResponse))]
[JsonSerializable(typeof(LoginSuccessResponse))]
[JsonSerializable(typeof(MfaRequiredResponse))]
[JsonSerializable(typeof(MfaSetupRequiredResponse))]
[JsonSerializable(typeof(SessionResponse))]
[JsonSerializable(typeof(ActiveSessionsResponse))]
[JsonSerializable(typeof(RevokeSessionsResponse))]
[JsonSerializable(typeof(List<AppLinkResponse>))]
[JsonSerializable(typeof(ConfirmEmailResponse))]
[JsonSerializable(typeof(ResetPasswordResponse))]
[JsonSerializable(typeof(UserIdentityResponse))]
[JsonSerializable(typeof(SsoCheckResponse))]
[JsonSerializable(typeof(SsoProviderListResponse))]
[JsonSerializable(typeof(PasswordPolicyResponse))]
[JsonSerializable(typeof(MfaStatusResponse))]
[JsonSerializable(typeof(TotpSetupResponse))]
[JsonSerializable(typeof(WebAuthnSetupResponse))]
[JsonSerializable(typeof(WebAuthnConfirmResponse))]
[JsonSerializable(typeof(RecoveryCodesResponse))]
[JsonSerializable(typeof(DeviceAuthorizationResponse))]
[JsonSerializable(typeof(DeviceApprovedResponse))]
[JsonSerializable(typeof(DeviceInfoResponse))]
[JsonSerializable(typeof(IntrospectionInactiveResponse))]
[JsonSerializable(typeof(ConsentInfoResponse))]
[JsonSerializable(typeof(BackChannelLogoutResult))]
[JsonSerializable(typeof(UserDetailResponse))]
[JsonSerializable(typeof(UserUpdateResponse))]
[JsonSerializable(typeof(ProfileResponse))]
[JsonSerializable(typeof(RoleListResponse))]
[JsonSerializable(typeof(UserRolesResponse))]
[JsonSerializable(typeof(RoleMembersResponse))]
[JsonSerializable(typeof(UserSummary))]
[JsonSerializable(typeof(UserSearchResponse))]
[JsonSerializable(typeof(UserListResponse))]
[JsonSerializable(typeof(UserExistsResponse))]
[JsonSerializable(typeof(ScopeListResponse))]
[JsonSerializable(typeof(Scope))]
[JsonSerializable(typeof(OAuthClient))]
[JsonSerializable(typeof(List<OAuthClient>))]
[JsonSerializable(typeof(Authagonal.Server.Endpoints.Admin.ProvisioningAppRequest))]
[JsonSerializable(typeof(Authagonal.Server.Endpoints.Admin.ProvisioningAppView))]
[JsonSerializable(typeof(List<Authagonal.Server.Endpoints.Admin.ProvisioningAppView>))]
[JsonSerializable(typeof(Authagonal.Server.Endpoints.Admin.ProvisioningTestPayload))]
[JsonSerializable(typeof(Authagonal.Server.Endpoints.Admin.ProvisioningTestResult))]
[JsonSerializable(typeof(Authagonal.Server.Endpoints.Admin.ProvisioningAppListResponse))]
[JsonSerializable(typeof(Authagonal.Server.Endpoints.Admin.ProvisioningAppDeleteResponse))]
[JsonSerializable(typeof(Authagonal.Server.Endpoints.Admin.AgentProfileRequest))]
[JsonSerializable(typeof(Authagonal.Server.Endpoints.Admin.AgentProfileView))]
[JsonSerializable(typeof(Authagonal.Server.Endpoints.Admin.AgentProfileListResponse))]
[JsonSerializable(typeof(Authagonal.Server.Endpoints.Admin.EffectiveGrantResponse))]
[JsonSerializable(typeof(AgentConsentRequest))]
[JsonSerializable(typeof(AgentConsentInfoResponse))]
[JsonSerializable(typeof(AgentConsentView))]
[JsonSerializable(typeof(AgentConsentListResponse))]
[JsonSerializable(typeof(ApprovalDecisionRequest))]
[JsonSerializable(typeof(ApprovalListResponse))]
[JsonSerializable(typeof(ClientRegistrationRequest))]
[JsonSerializable(typeof(ClientRegistrationResponse))]
[JsonSerializable(typeof(ScimTokenCreatedResponse))]
[JsonSerializable(typeof(ScimTokenListResponse))]
// Email
[JsonSerializable(typeof(ResendEmailRequest))]
// Token response
[JsonSerializable(typeof(TokenResponse))]
// Auth request DTOs
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(RegisterRequest))]
[JsonSerializable(typeof(PendingClaimData))]
[JsonSerializable(typeof(ConfirmEmailRequest))]
[JsonSerializable(typeof(ForgotPasswordRequest))]
[JsonSerializable(typeof(ResetPasswordRequest))]
[JsonSerializable(typeof(ProfileUpdateRequest))]
[JsonSerializable(typeof(MfaVerifyRequest))]
[JsonSerializable(typeof(PasswordlessCompleteRequest))]
[JsonSerializable(typeof(TotpConfirmRequest))]
[JsonSerializable(typeof(WebAuthnConfirmRequest))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
internal partial class AuthagonalJsonContext : JsonSerializerContext
{
}
